name = "clap"
version = "0.1.0"
defaultTargets = ["Clap"]

[[lean_lib]]
name = "Clap"
leanOptions = [
  { name = "linter.unusedVariables", value = true },
  { name = "autoImplicit", value = false },
]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.26.0-rc2"
